[uwsgi]
module = app:application
master = true
processes = 2
threads = 4
vacuum = true
socket = 127.0.0.1:9101
protocol = http
chmod-socket = 666
buffer-size = 65535
enable-threads = true
lazy-apps = true